version: '3'

services:
  api:
    container_name: file-service
    restart: on-failure
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env

  postgres:
    container_name: files_postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-db:/data/postgres
    ports:
      - "5432:5432"